### ISSUE TITLE
make checking slice length simple?

### ISSUE THREAD

**Issue by hao1118** [CloudyKit/jet#39] opened 2016-10-01 04:02 UTC
{{if myslice}} or {{if len(myslice)>0}}...{{end}} not working, have to use {{if isset(len(myslice)>0)}}...{{end}}, can it be simple just like {{if mystring}}?

**Comment by annismckenzie** [comment] 2016-10-01 05:42
That makes no sense, both the `if` and the `len` expression are heavily tested but just to be sure I added a test case – see #40. The test case does not fail. What version of Jet are you using?

**Comment by annismckenzie** [comment] 2016-10-01 11:24
Could this have the same root cause as in #38? Did you by chance try to test the length of a slice in a context object? This functionality is definitely and 100% working.

**Comment by jhsx** [comment] 2016-10-01 11:37
``` {{if myslice}} or {{if len(myslice)>0}} ``` will work if ``` myslice``` was defined before or passed in the VarMap.

**Comment by hao1118** [comment] 2016-10-01 11:48
Yes I test the length of a slice in a context object, out of scope too as in range? Then I have to use VarMap afterwards ;-)
GOOD LUCK Buddies!

**Comment by annismckenzie** [comment] 2016-10-01 11:52
Alright then. Can you close this issue? :)

**Closed** 2016-10-01 11:52 UTC
