### ISSUE TITLE
Is the word 'content' the keyword of the jet?

### ISSUE THREAD

**Issue by dxvgef** [CloudyKit/jet#71] opened 2017-11-09 15:09 UTC
My Go code like this:
`vars.Set("content", &content)`
template file code like this:
`{{content.ID}}`
Output error: ...... unexpected {{content}}

I changed the template variable name from 'content' to 'content2', I can work.
Is the word 'content' the keyword of the jet?

**Comment by jhsx** [comment] 2017-11-10 20:08
Hi, yes.

**Comment by toby3d** [comment] 2017-11-27 13:14
Duplicate of #65

**Comment by annismckenzie** [comment] 2018-07-03 07:56
Closing as a duplicate of #65 – I'll fix that over there.

**Closed by annismckenzie** 2018-07-03 07:56 UTC
