### ISSUE TITLE
I can custom Delims?

### ISSUE THREAD

**Issue by dxvgef** [CloudyKit/jet#76] opened 2018-02-15 13:00 UTC
I want change {{...}} to [[...]], how i should i do?

**Comment by xserve98** [comment] 2018-03-18 07:51
This item does not seem to have been maintained

**Comment by xserve98** [comment] 2018-03-18 07:52
I also have this need #68

**Comment by annismckenzie** [comment] 2018-03-18 13:48
Sorry about the silence to both of you. Let me see whether I can get ahold of José next week. Hang tight. 😅

**Comment by annismckenzie** [comment] 2018-05-12 08:05
@jhsx Can you make a decision about whether you ever want to support custom delimiters? If not, we should clearly state that here as well as in #68 and I'd add a section in the readme.

**Comment by dxvgef** [comment] 2018-05-12 16:40
@annismckenzie I think it is necessary to support custom delimiters. The default delimiters conflict with the JS framework.

**Comment by jhsx** [comment] 2018-05-14 14:13
@dxvgef @annismckenzie i am in favor of support custom delimiters, is someone interested in send a pull request ?

**Comment by annismckenzie** [comment] 2018-07-03 08:01
Closing as a duplicate of #68. I'll take care of implementing it there.

**Closed by annismckenzie** 2018-07-03 08:01 UTC

**Comment by annismckenzie** [comment] 2018-07-03 22:34
A PR implementing this feature is now open: #91. Anyone still in need of this and would be able to test it?
